# Languages
#   Create a section for each of your site's languages.

# 中文（默认语言）
zh:
  languageCode: zh-Hans
  languageName: 中文
  weight: 1
  title: 王文亮实验室

# 英文（可选）
en:
  languageCode: en-us
  languageName: English
  weight: 2
  title: Wang Wenliang Lab