# 语言配置

# 中文（唯一语言）
zh:
  languageCode: zh-Hans
  languageName: 中文
  weight: 1
  title: 王文靓实验室
  params:
    description: 王文靓实验室官方网站
  menu:
    main:
      - name: 首页
        url: '#about'
        weight: 10
      - name: 研究团队
        url: people
        weight: 20
      - name: 联系我们
        url: '#contact'
        weight: 30